# Usa la imagen oficial de Nginx basada en Alpine (ligera)
FROM nginx:alpine

# Copia los archivos estáticos a la carpeta de publicación de Nginx
COPY ./ /usr/share/nginx/html

# Redirigir el puerto en caso de ser necesario
EXPOSE 80
